export const listToImport = {
  id: 81,
  name: "Míralos Juzgar a los Otros",
  description:
    "películas dónde el conflicto principal gira en torno a un juicio o procedimiento judicial, ya sea civil, penal, constitucional, militar o laboral",
  link: "",
  ext_link: "",
  img: "https://cineoculto.com/wp-content/uploads/2019/05/12-Angry-Men-Fuente-The-405.jpg",
  by: "Juan Andrés",
  words: "morvip juzgar",
  movies: [
    {
      id: 709,
      name: "Legally Blonde",
      year: "2001",
      cast: "Reese Witherspoon,Luke Wilson,Selma Blair,Matthew Davis,Victor Garber,",
      imdb_id: "tt0250494",
      director: "Robert Luketic",
      link: "https://letterboxd.com/film/legally-blonde/",
      words: "levantar alegria moria juzgar",
      details: "",
    },
    {
      id: 1034,
      name: "Kramer vs. Kramer",
      year: "1979",
      cast: "Dustin Hoffman,Meryl Streep,Jane Alexander,Justin Henry,Howard Duff,",
      imdb_id: "tt0079417",
      director: "Robert Benton",
      link: "https://letterboxd.com/film/kramer-vs-kramer/",
      words: "bajon corchazo juzgar",
      details: "",
    },
    {
      id: 1166,
      name: "Philadelphia",
      year: "1993",
      cast: "Tom Hanks, Denzel Washington, Roberta Maxwell",
      imdb_id: "tt0107818",
      director: "Jonathan Demme",
      link: "https://letterboxd.com/film/philadelphia/",
      words: "bajon corchazo juzgar",
      details: "",
    },
    {
      id: 2100,
      name: "To Kill a Mockingbird",
      year: "1962",
      cast: "Gregory Peck,John Megna,Frank Overton,Rosemary Murphy,Ruth White,Brock Peters,Estelle Evans,Paul Fix,",
      imdb_id: "tt0056592",
      director: "Robert Mulligan",
      link: "imdb.com/title/tt0056592/",
      words: "MiralosMorir39 juzgar",
      details: "",
    },
    {
      id: 2417,
      name: "JFK",
      year: "1991",
      cast: "Kevin Costner,Tommy Lee Jones,Gary Oldman,Kevin Bacon,Michael Rooker,Jack Lemmon,Laurie Metcalf,",
      imdb_id: "tt0102138",
      director: "Oliver Stone",
      link: "-",
      words: "moria juzgar",
      details: "-",
    },
    {
      id: 2493,
      name: "A Few Good Men",
      year: "1992",
      cast: "Tom Cruise,Jack Nicholson,Demi Moore,Kevin Bacon,Kiefer Sutherland,Kevin Pollak,James Marshall,",
      imdb_id: "tt0104257",
      director: "Rob Reiner",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2494,
      name: "Witness for the Prosecution",
      year: "1957",
      cast: "Tyrone Power,Marlene Dietrich,Charles Laughton,Elsa Lanchester,John Williams,Henry Daniell,Ian Wolfe,",
      imdb_id: "tt0051201",
      director: "Billy Wilder",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2495,
      name: "A Separation",
      year: "2011",
      cast: "Leila Hatami,Payman Maadi,Shahab Hosseini,Sare Bayat,Sarina Farhadi,Babak Karimi,Ali-Asghar Shahbazi,",
      imdb_id: "tt1832382",
      director: "Asghar Farhadi",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2496,
      name: "Inherit the Wind",
      year: "1960",
      cast: "Spencer Tracy,Fredric March,Gene Kelly,Dick York,Donna Anderson,Harry Morgan,Claude Akins,",
      imdb_id: "tt0053946",
      director: "Stanley Kramer",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2497,
      name: "A Time to Kill",
      year: "1996",
      cast: "Matthew McConaughey,Sandra Bullock,Samuel L. Jackson,Kevin Spacey,Ashley Judd,Donald Sutherland,Oliver Platt,",
      imdb_id: "tt0117913",
      director: "Joel Schumacher",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2498,
      name: "Anatomy of a Murder",
      year: "1959",
      cast: "James Stewart,Lee Remick,Ben Gazzara,Arthur O'Connell,Eve Arden,Kathryn Grant,George C. Scott,",
      imdb_id: "tt0052561",
      director: "Otto Preminger",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2499,
      name: "The Exorcism of Emily Rose",
      year: "2005",
      cast: "Laura Linney,Tom Wilkinson,Campbell Scott,Jennifer Carpenter,Kenneth Welsh,Mary Beth Hurt,Colm Feore,",
      imdb_id: "tt0404032",
      director: "Scott Derrickson",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2500,
      name: "Paths of Glory",
      year: "1957",
      cast: "Kirk Douglas,Ralph Meeker,Adolphe Menjou,George Macready,Wayne Morris,Richard Anderson,Joe Turkel,",
      imdb_id: "tt0050825",
      director: "Stanley Kubrick",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2501,
      name: "Presumed Innocent",
      year: "1990",
      cast: "Brian Dennehy,Harrison Ford,Bonnie Bedelia,Raul Julia,Paul Winfield,Greta Scacchi,John Spencer,",
      imdb_id: "tt0100404",
      director: "Alan J. Pakula",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2502,
      name: "12 Angry Men",
      year: "1957",
      cast: "Martin Balsam,John Fiedler,Lee J. Cobb,E.G. Marshall,Jack Klugman,Edward Binns,Jack Warden,",
      imdb_id: "tt0050083",
      director: "Sidney Lumet",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2503,
      name: "Primal Fear",
      year: "1996",
      cast: "Richard Gere,Laura Linney,John Mahoney,Alfre Woodard,Frances McDormand,Edward Norton,Terry O'Quinn,",
      imdb_id: "tt0117381",
      director: "Gregory Hoblit",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2504,
      name: "Sleepers",
      year: "1996",
      cast: "Kevin Bacon,Billy Crudup,Robert De Niro,Ron Eldard,Minnie Driver,Vittorio Gassman,Dustin Hoffman,",
      imdb_id: "tt0117665",
      director: "Barry Levinson",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2505,
      name: "Town Without Pity",
      year: "1961",
      cast: "Kirk Douglas,Barbara Rütting,Christine Kaufmann,Hans Nielsen,Ingrid van Bergen,Robert Blake,Richard Jaeckel,",
      imdb_id: "tt0055539",
      director: "Gottfried Reinhardt",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2506,
      name: "The Trial of the Chicago 7",
      year: "2020",
      cast: "Eddie Redmayne,Sacha Baron Cohen,Joseph Gordon-Levitt,Michael Keaton,Frank Langella,John Carroll Lynch,Mark Rylance,",
      imdb_id: "tt1070874",
      director: "Aaron Sorkin",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2507,
      name: "The Court-Martial of Billy Mitchell",
      year: "1955",
      cast: "Gary Cooper,Charles Bickford,Ralph Bellamy,Rod Steiger,Elizabeth Montgomery,Fred Clark,James Daly,",
      imdb_id: "tt0047956",
      director: "Otto Preminger",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2508,
      name: "Breaker Morant",
      year: "1980",
      cast: "Edward Woodward,Jack Thompson,John Waters,Bryan Brown,Charles Tingwell,Terence Donovan,Vincent Ball,",
      imdb_id: "tt0080310",
      director: "Bruce Beresford",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2509,
      name: "The Juror",
      year: "1996",
      cast: "Demi Moore,Alec Baldwin,Joseph Gordon-Levitt,Anne Heche,James Gandolfini,Lindsay Crouse,Tony Lo Bianco,",
      imdb_id: "tt0116731",
      director: "Brian Gibson",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2510,
      name: "Rashomon",
      year: "1950",
      cast: "Toshiro Mifune,Machiko Kyō,Takashi Shimura,Masayuki Mori,Minoru Chiaki,Kichijirô Ueda,Noriko Honma,",
      imdb_id: "tt0042876",
      director: "Akira Kurosawa",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2511,
      name: "Runaway Jury",
      year: "2003",
      cast: "John Cusack,Gene Hackman,Dustin Hoffman,Rachel Weisz,Bruce Davison,Bruce McGill,Jeremy Piven,",
      imdb_id: "tt0313542",
      director: "Gary Fleder",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2512,
      name: "Harakiri",
      year: "1962",
      cast: "Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurō Tamba,Masao Mishima,Ichirô Nakatani,Kei Satō,",
      imdb_id: "tt0056058",
      director: "Masaki Kobayashi",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2513,
      name: "Double Jeopardy",
      year: "1999",
      cast: "Tommy Lee Jones,Ashley Judd,Bruce Greenwood,Annabeth Gish,Benjamin Weir,Spencer Treat Clark,Roma Maffia,",
      imdb_id: "tt0150377",
      director: "Bruce Beresford",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2514,
      name: "Judgment at Nuremberg",
      year: "1961",
      cast: "Spencer Tracy,Burt Lancaster,Richard Widmark,Marlene Dietrich,Maximilian Schell,Judy Garland,Montgomery Clift,",
      imdb_id: "tt0055031",
      director: "Stanley Kramer",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2515,
      name: "The Merchant of Venice",
      year: "2004",
      cast: "Al Pacino,Jeremy Irons,Joseph Fiennes,Lynn Collins,Zuleikha Robinson,Kris Marshall,Charlie Cox,",
      imdb_id: "tt0379889",
      director: "Michael Radford",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2516,
      name: "Rules of Engagement",
      year: "2000",
      cast: "Tommy Lee Jones,Samuel L. Jackson,Guy Pearce,Ben Kingsley,Bruce Greenwood,Anne Archer,Blair Underwood,",
      imdb_id: "tt0160797",
      director: "William Friedkin",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2517,
      name: "The Paradine Case",
      year: "1947",
      cast: "Gregory Peck,Ann Todd,Charles Laughton,Charles Coburn,Ethel Barrymore,Louis Jourdan,Alida Valli,",
      imdb_id: "tt0039694",
      director: "Alfred Hitchcock",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2518,
      name: "Liar Liar",
      year: "1997",
      cast: "Jim Carrey,Maura Tierney,Justin Cooper,Cary Elwes,Anne Haney,Jennifer Tilly,Amanda Donohoe,",
      imdb_id: "tt0119528",
      director: "Tom Shadyac",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2519,
      name: "The People vs. Larry Flynt",
      year: "1996",
      cast: "Woody Harrelson,Courtney Love,Edward Norton,Brett Harrelson,Donna Hanover,James Cromwell,Crispin Glover,",
      imdb_id: "tt0117318",
      director: "Miloš Forman",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2520,
      name: "Bridge of Spies",
      year: "2015",
      cast: "Tom Hanks,Mark Rylance,Amy Ryan,Alan Alda,Sebastian Koch,Austin Stowell,Billy Magnussen,",
      imdb_id: "tt3682448",
      director: "Steven Spielberg",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2521,
      name: "The Devil's Advocate",
      year: "1997",
      cast: "Keanu Reeves,Al Pacino,Charlize Theron,Jeffrey Jones,Judith Ivey,Connie Nielsen,Craig T. Nelson,",
      imdb_id: "tt0118971",
      director: "Taylor Hackford",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2522,
      name: "My Cousin Vinny",
      year: "1992",
      cast: "Joe Pesci,Ralph Macchio,Marisa Tomei,Mitchell Whitfield,Fred Gwynne,Lane Smith,Austin Pendleton,",
      imdb_id: "tt0104952",
      director: "Jonathan Lynn",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2523,
      name: "The Lincoln Lawyer",
      year: "2011",
      cast: "Matthew McConaughey,Marisa Tomei,Ryan Phillippe,William H. Macy,Josh Lucas,John Leguizamo,Michael Peña,",
      imdb_id: "tt1189340",
      director: "Brad Furman",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2524,
      name: "A Civil Action",
      year: "1998",
      cast: "John Travolta,Robert Duvall,Tony Shalhoub,William H. Macy,Zeljko Ivanek,Bruce Norris,John Lithgow,",
      imdb_id: "tt0120633",
      director: "Steven Zaillian",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2525,
      name: "Amistad",
      year: "1997",
      cast: "Morgan Freeman,Nigel Hawthorne,Anthony Hopkins,Djimon Hounsou,Matthew McConaughey,David Paymer,Pete Postlethwaite,",
      imdb_id: "tt0118607",
      director: "Steven Spielberg",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2526,
      name: "Conviction",
      year: "2010",
      cast: "Hilary Swank,Sam Rockwell,Minnie Driver,Melissa Leo,Peter Gallagher,Ari Graynor,Loren Dean,",
      imdb_id: "tt1244754",
      director: "Tony Goldwyn",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2527,
      name: "Erin Brockovich",
      year: "2000",
      cast: "Julia Roberts,Albert Finney,Aaron Eckhart,Marg Helgenberger,Cherry Jones,Veanne Cox,Conchata Ferrell,",
      imdb_id: "tt0195685",
      director: "Steven Soderbergh",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2528,
      name: "In the Name of the Father",
      year: "1993",
      cast: "Daniel Day-Lewis,Pete Postlethwaite,Emma Thompson,John Lynch,Corin Redgrave,Beatie Edney,John Benfield,",
      imdb_id: "tt0107207",
      director: "Jim Sheridan",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2529,
      name: "Fracture",
      year: "2007",
      cast: "Anthony Hopkins,Ryan Gosling,David Strathairn,Rosamund Pike,Embeth Davidtz,Billy Burke,Cliff Curtis,",
      imdb_id: "tt0488120",
      director: "Gregory Hoblit",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2530,
      name: "Red Corner",
      year: "1997",
      cast: "Richard Gere,Bai Ling,Bradley Whitford,Byron Mann,Peter Donat,Robert Stanton,Tsai Chin,",
      imdb_id: "tt0119994",
      director: "Jon Avnet",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2531,
      name: "Day of Wrath",
      year: "1943",
      cast: "Thorkild Roose,Lisbeth Movin,Preben Lerdorff Rye,Sigrid Neiiendam,Anna Svierkier,Albert Høeberg,Olaf Ussing,",
      imdb_id: "tt0036506",
      director: "Carl Theodor Dreyer",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2532,
      name: "The Star Chamber",
      year: "1983",
      cast: "Michael Douglas,Hal Holbrook,Yaphet Kotto,Sharon Gless,James B. Sikking,Joe Regalbuto,Don Calfa,",
      imdb_id: "tt0086356",
      director: "Peter Hyams",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2533,
      name: "Bad Luck Banging or Loony Porn",
      year: "2021",
      cast: "Katia Pascariu,Claudia Ieremia,Olimpia Mălai,Nicodim Ungureanu,Alexandru Potocean,Andi Vasluianu,Oana Maria Zaharia,",
      imdb_id: "tt14033502",
      director: "Radu Jude",
      link: "-",
      words: "juzgar",
      details: "-",
    },
    {
      id: 2534,
      name: "Scent of a Woman",
      year: "1992",
      cast: "Chris O'Donnell,Al Pacino,James Rebhorn,Gabrielle Anwar,Philip Seymour Hoffman,Bradley Whitford,Richard Venture,",
      imdb_id: "tt0105323",
      director: "Martin Brest",
      link: "-",
      words: "juzgar",
      details: "-",
    },
  ],
};
